### ISSUE TITLE
ws_expirer incorrectly removes allocations with the same name on different spaces

### ISSUE THREAD

**Issue by bryank-cs** [holgerBerger/hpc-workspace#116]
We had a user with an expired allocation in one space and a new allocation in a separate space with the same name. This caused `ws_expirer` to treat the second as `stray` and delete it. Here's the relevant lines from the log file:
```
   keeping /scratch/workspace/db/username-v1   (expires  Sat Nov 23 16:33:38 2024 )
  valid removed workspace /scratch/workspace/.removed/username-v1-1732287870
  deleting /scratch/workspace/db/.removed/username-v1-1732287870   (was released Fri Nov 22 15:04:30 2024 )
 OS.UNLINK /scratch/workspace/db/.removed/username-v1-1732287870
   deldir(fast) /scratch/workspace/.removed/username-v1-1732287870
  DELDIR /scratch/workspace/.removed/username-v1-1732287870
  stray workspace /scratch3/workspace/username-v1
  OS.RENAME /scratch3/workspace/username-v1 /scratch3/workspace/.removed/username-v1-1733270702
  stray removed workspace /scratch3/workspace/.removed/username-v1-1733270702
   deldir(fast) /scratch3/workspace/.removed/username-v1-1733270702
```
The configuration file:
```
workspaces:
  workspace:
    database: /scratch/workspace/db
    deleted: .removed
    duration: 30
    keeptime: 7
    maxextensions: 3
    spaces: [/scratch/workspace,/scratch3/workspace] 
    spaceselection: mostspace
```
