### ISSUE TITLE
Error: could not change permissions of database entry

### ISSUE THREAD

**Issue by staeglis** [holgerBerger/hpc-workspace#58]
Hi,

even on as test workspace on /tmp I get the same issue:
```
$ ws_allocate test 10
warn: you seem to have no access to your default workspace!?
Info: creating workspace.
Error: could not change permissions of database entry
/tmp/tmp-work/staeglis-test
remaining extensions  : 2
remaining time in days: 10
$ ws_list 
/usr/local/bin/ws_list:106: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(open('/etc/ws.conf'))
```

The config
```
admins: [root, metadm]                                  # users listed here can sees all workspaces with ws_list
clustername: cluster                                 # some name for the cluster
smtphost: localhost                                     # (my smtp server for sending mails)
dbgid: 16010                                            # a user id, this is the owner of some directories
dbuid: 1533                                             # a group id, this is the owner of some directories
default: tmp                                       # the workspace location to use for everybody
duration: 10                                            # (max duration in days, default for all workspaces )
maxextensions: 1                                        # (maximum number of times a user can ask for a extension)
workspaces:
  tmp:                                                  # name of the workspace location
    database: /tmp/tmp-db                               # DB directory
    deleted: .removed                                   # name of the subdirectory used for expired workspaces
    duration: 20                                        # max lifetime of a workspace in days
    keeptime: 7                                         # days to keep deleted data after expiration
    maxextensions: 2                                    # maximum number of times a user can ask for a extension
    spaces: [/tmp/tmp-work]                             # paths where workspaces are created, this is a list and path is picked randomly
    group_acl: [admin]
    user_acl: []
```

Best,
Stefan
